### ISSUE TITLE
Return urls of photo

### ISSUE THREAD

**Issue by Ourselp** [salvoventura/pyunsplash#11]
Hello !

First of all, nice projet, I use your library for one of my personal projet, easy to setup and use, so thanks a lot for that !

Was just wondering, for User.photos() can you add the "urls" property in return ? 

photo.link_download is not really usefull, it's simply https://unsplash.com/photos/{id} + '/download' which can be done quite easy without having to return a property.

However, returning the "urls" will be way more interesting because it will allow us the opportunity to literally download the picture and save them locally if necessary. 

Thanks in advance :D

**Comment by salvoventura** [comment]
Hello, and thanks for using PyUnsplash.

Each `Photo` object exposes three links: `link_html`, `link_download`, and `link_download_location` as properties.

If you want to use the Unsplash API (via this library) to _download_ the images, you **MUST** use the `link_download_location`, as per the [Unsplash Guidelines](https://help.unsplash.com/en/articles/2511258-guideline-triggering-a-download) (it's part of their agreement).

You can read more about this here:
[https://help.unsplash.com/en/articles/2511258-guideline-triggering-a-download](https://help.unsplash.com/en/articles/2511258-guideline-triggering-a-download)

If you could maybe provide an example to help understand your request, I will be happy to look into it.

Cheers,
Salvo

**Comment by Ourselp** [comment]
Woops, next time I will take more time to read the Unsplash Guidelines and the doc.

Just found out how to use properly the link 'https://api.unsplash.com/photos/{id}/download/' to save my photos locally.

Sorry and thanks for responding so fast

Best regards,
Philippe

**Comment by salvoventura** [comment]
No problem. Thanks for using the library! If you feel like it, maybe give it a star! :-)
