### ISSUE TITLE
No attribute as 'entries'

### ISSUE THREAD

**Issue by gargshantanu14** [salvoventura/pyunsplash#5]
while collections.has_next:
        for collection in collections.entries:
            photos = collection.photos
            for photo in photos.entries:
                print(collection.title, photo.link_download)
    # no need to specify per_page: will take from original object
    collections = collections.get_next_page()

    Traceback (most recent call last):
    File "<ipython-input-19-97290a89529d>", line 4, in <module>
    for photo in photos.entries:

    AttributeError: 'function' object has no attribute 'entries'

**Comment by salvoventura** [comment]
This is a documentation issue.
The following line:

    `photos = collection.photos`

should correctly read:

    `photos = collection.photos()`

I can see a case for making `collection.photos` a property. Let me think about it though.

**Comment by salvoventura** [comment]
Fixed in `master`.
